part of openapi.api;

enum PrivilegioCodigo {
  //WAYWALLET ADM
  WAY_CAD_LOJISTA,
  WAY_CAD_CARTEIRAS,
  WAY_TRANSACAO,
  WAY_IMP_CLI,
  WAY_EXP_FECHAMENTO,

//QUEST
  QUEST_PROD_VINCULADOS,
  QUEST_TRANSACAO,

//PRODUTO
  PROD_CAD,
  PROD_REMARCAR_PRECO,
  PROD_CAD_FICHA_TECNICA,
  PROD_MIX_PRODUTO,
  PROD_CAD_GRUPO,
  PROD_CAD_VARIACAO,
  PROD_CAD_TBL_PRECO,
  PROD_CAD_OBS,
  PROD_CAD_MENU,
  PROD_CAD_LOCAL_PRODUCAO,
  PROD_CAD_LOCAL_ESTOCAGEM,
  PROD_CAD_CARDAPIOS,
  PROD_CAD_DEP_FISCAL_ICMS,
  PROD_CAD_DEP_FISCAL_ISSQN,
  PROD_CAD_DEP_FISCAL_PISCOFINS,
  PROD_CAD_CLASS_FISCAL_CONTRIBUINTE,
  PROD_CAD_TRIB_UF,
  PROD_CAD_PROMOCAO,
  PROD_CAD_PROMOCAO_ITEM,
  PROD_CAD_VINC_FORNEC,

//ESTOQUE
  EST_PRODUCAO,
  EST_AJUSTE_SIMPLES,
  EST_AJUSTE_AVANCADO,
  EST_TRANSF_INTERNA,
  EST_TRANSF_EXTERNA,
  EST_DEV_VENDA,
  EST_DEV_COMPRA,
  EST_CAD_INVENTARIO,
  EST_CAD_SETOR,

//PESSOA
  PESSOA_CAD_CLI,
  PESSOA_CAD_REG,
  PESSOA_CAD_CLASSIFICACAO,
  PESSOA_CAD_RAMO_ATIVIDADE,
  PESSOA_CAD_STATUS_CREDITO,
  PESSOA_CAD_FORN,
  PESSOA_CAD_REPR,
  PESSOA_CAD_FUNC,
  PESSOA_CAD_EMPRESA,

//USUARIO
  PESSOA_CAD_USUARIO,
  PESSOA_CAD_USUARIO_PERFIL,
  PARAM_TROCA_PERFIL,

//FINANCEIRO
  FIN_FAT_CLI_VENDA,
  FIN_FAT_CLI_EXTRATO_CONTA,
  FIN_FAT_CLI_SALDO_CREDITOS,
  FIN_FAT_CLI_DEBITAR_LIMITE,
  FIN_CAD_TIT_RECEBER,
  FIN_RECEB_BAIXA_TITULO_RECEBER,
  FIN_CAD_TIT_PAGAR,
  FIN_RECEB_BAIXA_TITULO_PAGAR,
  FIN_ESTORNO,
  FIN_CAD_BANCO_CONTA,
  FIN_CONF_CAIXA,
  FIN_CAD_BANDEIRAS,
  FIN_CAD_TRANS_CARTAO,
  FIN_MAN_CREDITOS,
  FIN_DRE,
  FIN_CAD_DFC,
  FIN_CAD_ROYALTIES,
  FIN_CAD_PLANO_CONTAS,
  FIN_CAD_CENTRO_CUSTO,
  FIN_CAD_CC,

//FISCAL
  FISCAL_NF_EMISSAO,
  FISCAL_NF_LANCAMENTO,
  FISCAL_NF_CONS_GERENCIA,
  FISCAL_CAD_CFOP,
  FISCAL_PLANILHA_PRECO,
  FISCAL_TEF_ADMINISTRATIVO,

//CONS_REL
  CONS_ATENDIMENTOS,
  CONS_CAIXA,
  CONS_DASHBOARD,
  REL_CAD_PRODUTO,
  REL_CAD_CLIENTE,
  REL_CAD_TRIBUTACAO,
  REL_FAT_MONETARIO,
  REL_FAT_PROD_VENDIDOS,
  REL_FAT_CANC,
  REL_FAT_MODULOS,
  REL_FAT_FRANQUIA,
  REL_FAT_FISCAIS,
  REL_ESTOQUE,

//PARAMETROS
  PARAM_CAD_ESTACAO,
  PARAM_CAD_EMISSOR_FISCAL,
  PARAM_CAD_IMPRESSORA,
  PARAM_CAD_BALANCA,
  PARAM_CAD_CANAIS_VENDA,
  PARAM_CAD_FIN_COND_PAG,
  PARAM_LAYOUT_CONF,
  PARAM_CONTINGENCIA,
  PARAM_CAD_GERENCIADORES,
  PARAM_GERENCIAR_SESSOES_EXTRAS,
  PARAM_CAD_PLANO_PAGAMENTO,

//CONFIGURACAO_MODULOS
  CONF_CAD_MODULO,
  CONF_CAD_MODULO_POSICAO,
  CONF_PUB,
  CONF_CAD_PUB_EVENTO,
  CONF_CAD_PUB_PERFIL,
  CONF_PUB_CARTAO_PREVENDA,
  CONF_PUB_CARTAO_CHECKIN,

//CAIXA
  CX_SANGRIA,
  CX_SUPRIMENTO,
  CX_ABRIR_GAVETA,
  CX_CONFERE_TURNO,
  CX_VISUALIZAR_EXTRATO,
  CX_IMPRESSAO_RESUMO,
  CX_VISUALIZAR_RESUMO,
  CX_IMPRESSAO_COMPROVANTE,
  CX_CONTAGEM_SISTEMA,
  CX_VISUALIZAR_DIFERENCA,
  CX_DETALHES_LANCAMENTO,
  CX_BUSCAR_TURNOS,

//WAYCHEF
  WAYCHEF_MAPA_COMANDA,
  WAYCHEF_CANCELA_ITEM_ANTES,
  WAYCHEF_CANCELA_ITEM_DEPOIS,
  WAYCHEF_CANCELA_CONSUMO,
  WAYCHEF_SUSPENDER,
  WAYCHEF_CONTA_FECHAR,
  WAYCHEF_CONTA_REABRIR,
  WAYCHEF_ISENTA_TX_SERV,
  WAYCHEF_ISENTA_TX_FRETE,
  WAYCHEF_TRANSFERIR_JUNTAR,
  WAYCHEF_RESERVA_MESA,
  WAYCHEF_PREDESCONTO,
  WAYCHEF_EXPEDIR,
  WAYCHEF_EXPEDIR_CANCELAR,
  WAYCHEF_RELATORIOS,
  WAYCHEF_CONSUL_ATEND,
  WAYCHEF_CONFIGURAR,
  WAYCHEF_SERVICOS,

//VENDA
  VENDA_VENDER,
  VENDA_RECEBER,
  VENDA_DEBITAR_CLIENTE,
  VENDA_PERMITIR_FINALIZADORA,
  VENDA_PERMITIR_DESCONTO_EXCEDENTE_VENDA,
  VENDA_PERMITIR_DESCONTO_ITEM_GERAL,
  VENDA_PERMITIR_DESCONTO_ITEM_ITEM,
  VENDA_RECEBER_ITEM,
  VENDA_CANCELA,
  VENDA_INFORMA_QTDE,
  VENDA_ACRE_TOTAL,
  VENDA_DESC_TOTAL,
  VENDA_DESC_ITEM,

//PLATAFORMA
  PLAT_CAD_EMPRESAS,
  PLAT_CAD_TERMO_ACEITE,
  PLAT_CAD_TUTORIAIS,
  PLAT_CAD_VERSIONAMENTO,
  PLAT_CAD_CLIENTS,
  PLAT_CAD_DRIVERS_IMPRESSORA,
  PLAT_CAD_ICONES_PADRAO,
  PLAT_CAD_CONTRATOS,
  PLAT_CAD_CONTRATOS_EXTRAS,
  PLAT_CAD_BANCO,
  PLAT_CAD_PGTO_IFOOD,
  PLAT_CAD_CONFIG,
  PLAT_CAD_USUARIOS,
  PLAT_CAD_PERMISSOES_PADRAO,
  PLAT_TRANSACOES,
  PLAT_CAD_SITEF_REDES_ADQUIRENTES,
  PLAT_CAD_SITEF_BANDEIRAS,
  PLAT_CAD_FISCAL_ORIGEM_MERCADORIA,
  PLAT_CAD_FISCAL_CST,
  PLAT_CAD_FISCAL_CSOSN,
  PLAT_CAD_FISCAL_PIS_COFINS,
  PLAT_CAD_FISCAL_NCM,
  PLAT_CAD_FISCAL_CEST,
  PLAT_CAD_FISCAL_CFOP_PADRAO,
  PLAT_CAD_INF_COMP_DOC_FISCAL,
  PLAT_CAD_EMISSOR_FISCAL,
  PLAT_CAD_UF,
  PLAT_FISCAL_IBPT,
  PLAT_RELATORIOS
}

extension PrivilegioCodigoExtension on PrivilegioCodigo{
  String get name => describeEnum(this);

  bool equals(PrivilegioCodigo privilegioCodigo) => this == privilegioCodigo;

// String get descricao{
//   switch(this){
//
//
//   }
// }
}
