name: waycard
description: Waywallet Híbrido para controle de cartões waybe desenvolvido em Flutter pela Waybe
publish_to: none
version: 3.0.00+3000

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  models:
    path: ../models
  utils:
    path: ../utils
  requester:
    path: ../requester

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  google_sign_in: ^5.3.1
  cloud_firestore: ^3.1.15
  flutter_login_facebook: ^1.4.1
  bloc_pattern: ^3.0.0+1
  percent_indicator: ^4.2.2
  shared_preferences: ^2.0.15
  mask_text_input_formatter: ^2.3.0
  cpf_cnpj_validator: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.11
  lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icone_waywallet.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
